[build]
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "camera=(self)"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
