create extension if not exists pgcrypto;
create table if not exists public.inventory_items(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,game text not null default 'Pokémon',language text not null default 'de',name text not null,set_name text not null default '',card_number text not null default '',condition text not null default 'NM',variant text not null default 'Normal',quantity integer not null default 1 check(quantity>=0),location text not null default '',purchase_price numeric(12,2),market_value numeric(12,2),notes text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.transactions(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,kind text not null check(kind in('purchase','sale','expense')),inventory_item_id uuid references public.inventory_items(id) on delete set null,description text not null,transaction_date date not null default current_date,quantity integer not null default 1 check(quantity>0),amount numeric(12,2) not null default 0 check(amount>=0),fees numeric(12,2) not null default 0 check(fees>=0),platform text not null default '',notes text not null default '',created_at timestamptz not null default now());
create index if not exists inventory_items_user_id_idx on public.inventory_items(user_id);create index if not exists inventory_items_name_idx on public.inventory_items(name);create index if not exists transactions_user_date_idx on public.transactions(user_id,transaction_date desc);
alter table public.inventory_items enable row level security;alter table public.transactions enable row level security;
drop policy if exists "Users manage own inventory" on public.inventory_items;create policy "Users manage own inventory" on public.inventory_items for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists "Users manage own transactions" on public.transactions;create policy "Users manage own transactions" on public.transactions for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
grant usage on schema public to anon,authenticated;grant select,insert,update,delete on public.inventory_items to authenticated;grant select,insert,update,delete on public.transactions to authenticated;
alter table public.inventory_items add column if not exists selling_price numeric(12,2);
alter table public.inventory_items add column if not exists cardmarket_product_id bigint;
alter table public.inventory_items add column if not exists source text not null default 'manual';
alter table public.transactions add column if not exists import_batch text;
create index if not exists inventory_cardmarket_product_idx on public.inventory_items(user_id,cardmarket_product_id);
create index if not exists transactions_import_batch_idx on public.transactions(user_id,import_batch);
alter table public.transactions add column if not exists external_reference text;
alter table public.transactions add column if not exists transaction_group uuid;
alter table public.transactions drop constraint if exists transactions_kind_check;
alter table public.transactions add constraint transactions_kind_check check(kind in('purchase','sale','expense','adjustment'));
create index if not exists transactions_group_idx on public.transactions(user_id,transaction_group);
alter table public.transactions add column if not exists voided_at timestamptz;
alter table public.transactions add column if not exists void_reason text;
alter table public.transactions add column if not exists shipping_cost numeric(12,2) not null default 0;
alter table public.transactions add column if not exists shipping_charged numeric(12,2) not null default 0;
create index if not exists transactions_active_import_idx on public.transactions(user_id,import_batch,voided_at);
alter table public.inventory_items add column if not exists is_test boolean not null default false;
alter table public.transactions add column if not exists is_test boolean not null default false;
create or replace function public.set_card_collector_mode() returns trigger language plpgsql set search_path=public as $$ begin new.is_test := coalesce(nullif(current_setting('request.headers',true),'')::jsonb ->> 'x-app-mode','live')='test'; return new; end; $$;
drop trigger if exists inventory_items_set_mode on public.inventory_items;
create trigger inventory_items_set_mode before insert on public.inventory_items for each row execute function public.set_card_collector_mode();
drop trigger if exists transactions_set_mode on public.transactions;
create trigger transactions_set_mode before insert on public.transactions for each row execute function public.set_card_collector_mode();
create index if not exists inventory_items_mode_idx on public.inventory_items(user_id,is_test);
create index if not exists transactions_mode_idx on public.transactions(user_id,is_test);
